# 版权 @2020 柴树杉。

[package]
name = "hello-rust-wasm"
version = "0.1.0"
authors = ["chai2010 <chaishushan@gmail.com>"]
edition = "2018"
build = "build.rs"

[build-dependencies]
cc = "1.0"

[dependencies]
